# Define the default driver
#webdriver.driver=phantomjs

# Appears at the top of the reports
serenity.project.name = Lab05 Web Testing
webdriver.autodownload = false
webdriver.driver = chrome
headless.mode = false

# Root package for any JUnit acceptance tests
serenity.test.root=demo.features

# Customise your riequirements hierarchy
#serenity.requirement.types=feature, story

# Run the tests without calling webdriver - useful to check your JUnit wireing
#serenity.dry.run=true

# Customise browser size
#serenity.browser.height = 1200
#serenity.browser.width = 1200

webdriver.chrome.driver = src/test/resources/windows/chromedriver.exe

webdriver.timeouts.implicitlywait = 15000
webdriver.wait.for.timeout = 15000
chrome.switches = --ignore-certificate-errors