// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGBD_lab3.Models;

#nullable disable

namespace SGBD_lab3.Migrations
{
    [DbContext(typeof(TransportContext))]
    [Migration("20260511081403_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGBD_lab3.Models.Angajat", b =>
                {
                    b.Property<string>("Cnp")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Bonusuri")
                        .HasColumnType("float");

                    b.Property<string>("Caen")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Functie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salar")
                        .HasColumnType("float");

                    b.HasKey("Cnp");

                    b.HasIndex("Caen")
                        .HasDatabaseName("idx_angajati_caen");

                    b.HasIndex("Salar")
                        .HasDatabaseName("idx_angajati_salar");

                    b.HasIndex("Caen", "Salar")
                        .HasDatabaseName("idx_angajati_caen_salar");

                    b.ToTable("Angajati");
                });

            modelBuilder.Entity("SGBD_lab3.Models.FirmaTransport", b =>
                {
                    b.Property<string>("Caen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SediuFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sediu_firma");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Caen");

                    b.ToTable("Firma_transport");
                });

            modelBuilder.Entity("SGBD_lab3.Models.Angajat", b =>
                {
                    b.HasOne("SGBD_lab3.Models.FirmaTransport", "FirmaTransport")
                        .WithMany("Angajati")
                        .HasForeignKey("Caen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirmaTransport");
                });

            modelBuilder.Entity("SGBD_lab3.Models.FirmaTransport", b =>
                {
                    b.Navigation("Angajati");
                });
#pragma warning restore 612, 618
        }
    }
}
